### ISSUE TITLE
can not run command on angular 14 vs nodejs v18.12.1 npm 8.19.2

### ISSUE THREAD

**Issue by hungbu** [manfredsteyer/angular-crud#49]
[error] Error: Collection "angular-crud" cannot be resolved.
    at SchematicEngineHost.resolve (C:\laragon\www\angular-crud\demo\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:75:19)
    at SchematicEngineHost._resolveCollectionPath (C:\laragon\www\angular-crud\demo\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:80:37)
    at SchematicEngineHost.createCollectionDescription (C:\laragon\www\angular-crud\demo\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:118:27)
    at SchematicEngine._createCollectionDescription (C:\laragon\www\angular-crud\demo\node_modules\@angular-devkit\schematics\src\engine\engine.js:162:40)
    at SchematicEngine.createCollection (C:\laragon\www\angular-crud\demo\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:43)
    at GenerateCommand.getCollection (C:\laragon\www\angular-crud\demo\node_modules\@angular\cli\models\schematic-command.js:143:35)
    at GenerateCommand.initialize (C:\laragon\www\angular-crud\demo\node_modules\@angular\cli\models\schematic-command.js:62:37)
    at async GenerateCommand.initialize (C:\laragon\www\angular-crud\demo\node_modules\@angular\cli\commands\generate-impl.js:20:9)
    at async GenerateCommand.validateAndRun (C:\laragon\www\angular-crud\demo\node_modules\@angular\cli\models\command.js:121:22)
    at async Object.runCommand (C:\laragon\www\angular-crud\demo\node_modules\@angular\cli\models\command-runner.js:224:24)

**Comment by mraible** [comment]
Please provide the steps to reproduce this error. I can't fix anything if I can reproduce it!

**Comment by hungbu** [comment]
sorry,
it's my issue
